const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

let inputData = '';
process.stdin.on('data', (chunk) => { inputData += chunk.toString(); });
process.stdin.on('end', () => {
    try {
        const payload = JSON.parse(inputData);

        // New format: files + command (generated by runner.ts)
        if (payload.files && payload.command) {
            runGeneratedRunner(payload.files, payload.command);
            return;
        }

        // Legacy format: code + language + testCases
        executeLegacy(payload);
    } catch (err) {
        console.error(JSON.stringify({ error: err.message }));
        process.exit(1);
    }
});

function runGeneratedRunner(files, command) {
    // Write all files to /tmp
    for (const [name, content] of Object.entries(files)) {
        const dir = path.dirname(name);
        if (dir !== '.') {
            fs.mkdirSync(path.join('/tmp', dir), { recursive: true });
        }
        fs.writeFileSync(path.join('/tmp', name), content);
    }

    // Run the command (command uses /tmp paths already)
    try {
        const stdout = execSync(command, {
            cwd: '/tmp',
            timeout: 25000,
            stdio: 'pipe',
            encoding: 'utf-8',
            maxBuffer: 10 * 1024 * 1024,
        });
        console.log(stdout);
    } catch (err) {
        const stderr = err.stderr ? err.stderr.toString() : '';
        const msg = (err.stdout || '').toString() + stderr || err.message;
        console.error(JSON.stringify({ error: msg, errorType: 'runtime_error' }));
        process.exit(1);
    }
}

function executeLegacy(data) {
    const extMap = {
        'javascript': 'js', 'typescript': 'ts', 'python': 'py',
        'java': 'java', 'cpp': 'cpp', 'c': 'c', 'go': 'go', 'rust': 'rs'
    };

    const ext = extMap[data.language] || 'txt';
    const fileName = '/tmp/solution.' + ext;
    fs.writeFileSync(fileName, data.code);

    const compileCmds = {
        'java': 'javac ' + fileName,
        'cpp': 'g++ -std=c++17 -O2 ' + fileName + ' -o /tmp/solution',
        'c': 'gcc -std=c11 -O2 ' + fileName + ' -o /tmp/solution',
        'go': 'go build -o /tmp/solution ' + fileName,
        'rust': 'rustc -C opt-level=2 ' + fileName + ' -o /tmp/solution'
    };

    if (compileCmds[data.language]) {
        try {
            execSync(compileCmds[data.language], { timeout: 15000, stdio: 'pipe' });
        } catch (err) {
            const msg = err.stderr ? err.stderr.toString() : err.message;
            console.error(JSON.stringify({ error: msg, errorType: 'compilation_error' }));
            process.exit(1);
        }
    }

    const runCmds = {
        'javascript': 'node ' + fileName,
        'typescript': 'ts-node ' + fileName,
        'python': 'python3 ' + fileName,
        'java': 'java ' + fileName.replace('.java', ''),
        'cpp': '/tmp/solution', 'c': '/tmp/solution', 'go': '/tmp/solution', 'rust': '/tmp/solution'
    };

    const cmd = runCmds[data.language];
    if (!cmd) {
        console.error(JSON.stringify({ error: 'Unsupported language', errorType: 'runtime_error' }));
        process.exit(1);
    }

    const results = [];
    for (const tc of (data.testCases || [])) {
        try {
            const out = execSync(cmd, { input: tc.input, encoding: 'utf-8', timeout: 5000, stdio: 'pipe' }).toString();
            results.push({
                input: tc.input, expected: tc.expected, actual: out,
                passed: out.trim() === tc.expected.trim()
            });
        } catch (err) {
            const stderr = err.stderr ? err.stderr.toString() : '';
            const msg = err.message || '';
            let errorType = 'runtime_error';
            if (msg.includes('timed out') || msg.includes('TIMEOUT') || msg.includes('timeout')) {
                errorType = 'timeout_error';
            }
            if (msg.includes('out of memory') || msg.includes('OutOfMemory') || msg.includes('Cannot allocate memory')) {
                errorType = 'memory_error';
            }
            results.push({
                input: tc.input, expected: tc.expected, actual: null,
                stderr, error: stderr || msg, errorType, passed: false
            });
        }
    }
    console.log(JSON.stringify({ results }));
}
