import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const sc = (py: string, java: string, cpp: string, c: string) => ({
  python: py.trim(),
  java: java.trim(),
  cpp: cpp.trim(),
  c: c.trim(),
});

const tc = (input: unknown, expected: unknown, hidden = false) => ({
  input: JSON.stringify(input),
  expectedOutput: JSON.stringify(expected),
  isHidden: hidden,
});

const problems: Array<{
  slug: string; title: string; difficulty: string; category: string;
  description: string; constraints: string; examples: any[]; tags: string[]; companies: string[];
  hints: string[]; editorial: string; complexity: any; acceptanceRate: number; submissionCount: number;
  isPublished: boolean; starterCode: Record<string, string>;
  testCases: Array<{ input: string; expectedOutput: string; isHidden: boolean }>;
}> = [
  {
    slug: `two-sum`,
    title: `Two Sum`,
    difficulty: `Easy`,
    category: `Arrays`,
    description: `Given an array of integers \`nums\` and an integer \`target\`, return indices of the two numbers that add up to \`target\`.\n\nYou may assume that each input has exactly one solution, and you may not use the same element twice.\n\n**Example 1:**\nInput: nums = [2,7,11,15], target = 9\nOutput: [0,1]\n\n**Example 2:**\nInput: nums = [3,2,4], target = 6\nOutput: [1,2]\n\n**Constraints:**\n- 2 ≤ nums.length ≤ 10⁴\n- -10⁹ ≤ nums[i] ≤ 10⁹\n- Only one valid answer exists.`,
    constraints: `- 2 ≤ nums.length ≤ 10⁴\n- -10⁹ ≤ nums[i] ≤ 10⁹\n- Only one valid answer exists.`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def two_sum(nums, target):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int[] twoSum(int[] nums, int target) {\n    // TODO: implement\n    return new int[0];\n  }\n}`,
      `class Solution {\npublic:\n  vector<int> twoSum(vector<int>& nums, int target) {\n    // TODO: implement\n    return {};\n  }\n};`,
      `int* twoSum(int* nums, int numsSize, int target, int* returnSize) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"nums":[2,7,11,15],"target":9}, [0,1]),
      tc({"nums":[3,2,4],"target":6}, [1,2]),
      tc({"nums":[3,3],"target":6}, [0,1]),
      tc({"nums":[-3,4,3,90],"target":0}, [0,2], true),
      tc({"nums":[0,4,3,0],"target":0}, [0,3], true),
    ],
  },
  {
    slug: `best-time-to-buy-and-sell-stock`,
    title: `Best Time to Buy and Sell Stock`,
    difficulty: `Easy`,
    category: `Arrays`,
    description: `You are given an array \`prices\` where \`prices[i]\` is the price of a given stock on the i-th day.\n\nYou want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.\n\nReturn the maximum profit you can achieve. If no profit is possible, return 0.\n\n**Example 1:**\nInput: prices = [7,1,5,3,6,4]\nOutput: 5\n\n**Example 2:**\nInput: prices = [7,6,4,3,1]\nOutput: 0\n\n**Constraints:**\n- 1 ≤ prices.length ≤ 10⁵\n- 0 ≤ prices[i] ≤ 10⁴`,
    constraints: `- 1 ≤ prices.length ≤ 10⁵\n- 0 ≤ prices[i] ≤ 10⁴`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def max_profit(prices):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int maxProfit(int[] prices) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int maxProfit(vector<int>& prices) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int maxProfit(int* prices, int pricesSize) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"prices":[7,1,5,3,6,4]}, 5),
      tc({"prices":[7,6,4,3,1]}, 0),
      tc({"prices":[1,2]}, 1),
      tc({"prices":[2,4,1]}, 2, true),
      tc({"prices":[1]}, 0, true),
    ],
  },
  {
    slug: `plus-one`,
    title: `Plus One`,
    difficulty: `Easy`,
    category: `Arrays`,
    description: `You are given a large integer represented as an integer array \`digits\`, where each \`digits[i]\` is the i-th digit. The digits are ordered from most significant to least significant.\n\nIncrement the large integer by one and return the resulting array.\n\n**Example 1:**\nInput: digits = [1,2,3]\nOutput: [1,2,4]\n\n**Example 2:**\nInput: digits = [4,3,2,1]\nOutput: [4,3,2,2]\n\n**Constraints:**\n- 1 ≤ digits.length ≤ 100\n- 0 ≤ digits[i] ≤ 9`,
    constraints: `- 1 ≤ digits.length ≤ 100\n- 0 ≤ digits[i] ≤ 9`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def plus_one(digits):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int[] plusOne(int[] digits) {\n    // TODO: implement\n    return new int[0];\n  }\n}`,
      `class Solution {\npublic:\n  vector<int> plusOne(vector<int>& digits) {\n    // TODO: implement\n    return {};\n  }\n};`,
      `int* plusOne(int* digits, int digitsSize, int* returnSize) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"digits":[1,2,3]}, [1,2,4]),
      tc({"digits":[4,3,2,1]}, [4,3,2,2]),
      tc({"digits":[9]}, [1,0]),
      tc({"digits":[9,9]}, [1,0,0], true),
      tc({"digits":[0]}, [1], true),
    ],
  },
  {
    slug: `single-number`,
    title: `Single Number`,
    difficulty: `Easy`,
    category: `Arrays`,
    description: `Given a non-empty array of integers \`nums\`, every element appears twice except for one. Find that single one.\n\nYou must implement a solution with linear runtime and constant extra space.\n\n**Example 1:**\nInput: nums = [2,2,1]\nOutput: 1\n\n**Example 2:**\nInput: nums = [4,1,2,1,2]\nOutput: 4\n\n**Constraints:**\n- 1 ≤ nums.length ≤ 3·10⁴\n- -3·10⁴ ≤ nums[i] ≤ 3·10⁴`,
    constraints: `- 1 ≤ nums.length ≤ 3·10⁴\n- -3·10⁴ ≤ nums[i] ≤ 3·10⁴`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def single_number(nums):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int singleNumber(int[] nums) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int singleNumber(vector<int>& nums) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int singleNumber(int* nums, int numsSize) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"nums":[2,2,1]}, 1),
      tc({"nums":[4,1,2,1,2]}, 4),
      tc({"nums":[1]}, 1),
      tc({"nums":[-1,-1,-2]}, -2, true),
      tc({"nums":[0,1,0,1,2]}, 2, true),
    ],
  },
  {
    slug: `valid-anagram`,
    title: `Valid Anagram`,
    difficulty: `Easy`,
    category: `Strings`,
    description: `Given two strings \`s\` and \`t\`, return \`true\` if \`t\` is an anagram of \`s\`, and \`false\` otherwise.\n\nAn anagram is a word formed by rearranging the letters of another word.\n\n**Example 1:**\nInput: s = "anagram", t = "nagaram"\nOutput: true\n\n**Example 2:**\nInput: s = "rat", t = "car"\nOutput: false\n\n**Constraints:**\n- 1 ≤ s.length, t.length ≤ 5·10⁴\n- s and t consist of lowercase English letters`,
    constraints: `- 1 ≤ s.length, t.length ≤ 5·10⁴\n- s and t consist of lowercase English letters`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def is_anagram(s, t):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean isAnagram(String s, String t) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool isAnagram(string s, string t) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool isAnagram(char* s, char* t) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"s":"anagram","t":"nagaram"}, true),
      tc({"s":"rat","t":"car"}, false),
      tc({"s":"a","t":"a"}, true, true),
      tc({"s":"a","t":"b"}, false, true),
      tc({"s":"ab","t":"a"}, false, true),
    ],
  },
  {
    slug: `contains-duplicate`,
    title: `Contains Duplicate`,
    difficulty: `Easy`,
    category: `HashMap`,
    description: `Given an integer array \`nums\`, return \`true\` if any value appears at least twice in the array, and \`false\` if every element is distinct.\n\n**Example 1:**\nInput: nums = [1,2,3,1]\nOutput: true\n\n**Example 2:**\nInput: nums = [1,2,3,4]\nOutput: false\n\n**Constraints:**\n- 1 ≤ nums.length ≤ 10⁵\n- -10⁹ ≤ nums[i] ≤ 10⁹`,
    constraints: `- 1 ≤ nums.length ≤ 10⁵\n- -10⁹ ≤ nums[i] ≤ 10⁹`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def contains_duplicate(nums):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean containsDuplicate(int[] nums) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool containsDuplicate(vector<int>& nums) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool containsDuplicate(int* nums, int numsSize) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"nums":[1,2,3,1]}, true),
      tc({"nums":[1,2,3,4]}, false),
      tc({"nums":[1,1,1,3,3,4,3,2,4,2]}, true),
      tc({"nums":[]}, false, true),
      tc({"nums":[1]}, false, true),
    ],
  },
  {
    slug: `ransom-note`,
    title: `Ransom Note`,
    difficulty: `Easy`,
    category: `HashMap`,
    description: `Given two strings \`ransomNote\` and \`magazine\`, return \`true\` if \`ransomNote\` can be constructed by using the letters from \`magazine\`. Each letter in \`magazine\` can only be used once.\n\n**Example 1:**\nInput: ransomNote = "a", magazine = "b"\nOutput: false\n\n**Example 2:**\nInput: ransomNote = "aa", magazine = "ab"\nOutput: false\n\n**Constraints:**\n- 1 ≤ ransomNote.length, magazine.length ≤ 10⁵\n- Both strings consist of lowercase English letters`,
    constraints: `- 1 ≤ ransomNote.length, magazine.length ≤ 10⁵\n- Both strings consist of lowercase English letters`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def can_construct(ransom_note, magazine):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean canConstruct(String ransomNote, String magazine) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool canConstruct(string ransomNote, string magazine) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool canConstruct(char* ransomNote, char* magazine) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"ransomNote":"a","magazine":"b"}, false),
      tc({"ransomNote":"aa","magazine":"ab"}, false),
      tc({"ransomNote":"aa","magazine":"aab"}, true),
      tc({"ransomNote":"aab","magazine":"baa"}, true, true),
      tc({"ransomNote":"abc","magazine":"ab"}, false, true),
    ],
  },
  {
    slug: `word-pattern`,
    title: `Word Pattern`,
    difficulty: `Easy`,
    category: `HashMap`,
    description: `Given a \`pattern\` and a string \`s\`, find if \`s\` follows the same pattern. A bijection must exist between each letter in pattern and each word in s.\n\n**Example 1:**\nInput: pattern = "abba", s = "dog cat cat dog"\nOutput: true\n\n**Example 2:**\nInput: pattern = "abba", s = "dog cat cat fish"\nOutput: false\n\n**Constraints:**\n- 1 ≤ pattern.length ≤ 300\n- 1 ≤ s.length ≤ 3000\n- pattern and s contain only lowercase letters and spaces`,
    constraints: `- 1 ≤ pattern.length ≤ 300\n- 1 ≤ s.length ≤ 3000\n- pattern and s contain only lowercase letters and spaces`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def word_pattern(pattern, s):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean wordPattern(String pattern, String s) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool wordPattern(string pattern, string s) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool wordPattern(char* pattern, char* s) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"pattern":"abba","s":"dog cat cat dog"}, true),
      tc({"pattern":"abba","s":"dog cat cat fish"}, false),
      tc({"pattern":"aaaa","s":"dog cat cat dog"}, false),
      tc({"pattern":"abba","s":"dog dog dog dog"}, false, true),
      tc({"pattern":"abc","s":"dog cat dog"}, false, true),
    ],
  },
  {
    slug: `valid-palindrome`,
    title: `Valid Palindrome`,
    difficulty: `Easy`,
    category: `Two Pointers`,
    description: `A phrase is a palindrome if it reads the same forward and backward after converting all uppercase letters to lowercase and removing all non-alphanumeric characters.\n\n**Example 1:**\nInput: s = "A man, a plan, a canal: Panama"\nOutput: true\n\n**Example 2:**\nInput: s = "race a car"\nOutput: false\n\n**Constraints:**\n- 1 ≤ s.length ≤ 2·10⁵\n- s consists of printable ASCII characters`,
    constraints: `- 1 ≤ s.length ≤ 2·10⁵\n- s consists of printable ASCII characters`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def is_palindrome(s):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean isPalindrome(String s) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool isPalindrome(string s) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool isPalindrome(char* s) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"s":"A man, a plan, a canal: Panama"}, true),
      tc({"s":"race a car"}, false),
      tc({"s":" "}, true),
      tc({"s":".,"}, true, true),
      tc({"s":"0P"}, false, true),
    ],
  },
  {
    slug: `move-zeroes`,
    title: `Move Zeroes`,
    difficulty: `Easy`,
    category: `Two Pointers`,
    description: `Given an integer array \`nums\`, move all 0's to the end while maintaining the relative order of non-zero elements. Do this in-place.\n\n**Example 1:**\nInput: nums = [0,1,0,3,12]\nOutput: [1,3,12,0,0]\n\n**Example 2:**\nInput: nums = [0]\nOutput: [0]\n\n**Constraints:**\n- 1 ≤ nums.length ≤ 10⁴`,
    constraints: `- 1 ≤ nums.length ≤ 10⁴`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def move_zeroes(nums):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public void moveZeroes(int[] nums) {\n    // TODO: implement\n    ;\n  }\n}`,
      `class Solution {\npublic:\n  void moveZeroes(vector<int>& nums) {\n    // TODO: implement\n    ;\n  }\n};`,
      `void moveZeroes(int* nums, int numsSize) {\n  // TODO: implement\n  ;\n}`,
    ),
    testCases: [
      tc({"nums":[0,1,0,3,12]}, [1,3,12,0,0]),
      tc({"nums":[0]}, [0]),
      tc({"nums":[1,0]}, [1,0]),
      tc({"nums":[0,0,1]}, [1,0,0], true),
      tc({"nums":[1,2,3]}, [1,2,3], true),
    ],
  },
  {
    slug: `remove-duplicates-from-sorted-array`,
    title: `Remove Duplicates from Sorted Array`,
    difficulty: `Easy`,
    category: `Two Pointers`,
    description: `Given a sorted array \`nums\`, remove duplicates in-place so each unique element appears once. Return the number of unique elements.\n\n**Example 1:**\nInput: nums = [1,1,2]\nOutput: 2\n\n**Example 2:**\nInput: nums = [0,0,1,1,1,2,2,3,3,4]\nOutput: 5\n\n**Constraints:**\n- 1 ≤ nums.length ≤ 3·10⁴\n- nums is sorted in non-decreasing order`,
    constraints: `- 1 ≤ nums.length ≤ 3·10⁴\n- nums is sorted in non-decreasing order`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def remove_duplicates(nums):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int removeDuplicates(int[] nums) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int removeDuplicates(vector<int>& nums) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int removeDuplicates(int* nums, int numsSize) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"nums":[1,1,2]}, 2),
      tc({"nums":[0,0,1,1,1,2,2,3,3,4]}, 5),
      tc({"nums":[1,2,3]}, 3, true),
      tc({"nums":[1,1,1]}, 1, true),
      tc({"nums":[]}, 0, true),
    ],
  },
  {
    slug: `valid-parentheses`,
    title: `Valid Parentheses`,
    difficulty: `Easy`,
    category: `Stack`,
    description: `Given a string \`s\` containing just the characters \`'('\`, \`')'\`, \`'{'\`, \`'}'\`, \`'['\` and \`']'\`, determine if the input string is valid. Open brackets must be closed by the same type in the correct order.\n\n**Example 1:**\nInput: s = "()"\nOutput: true\n\n**Example 2:**\nInput: s = "()[]{}"\nOutput: true\n\n**Constraints:**\n- 1 ≤ s.length ≤ 10⁴\n- s consists of parentheses only '()[]{}'`,
    constraints: `- 1 ≤ s.length ≤ 10⁴\n- s consists of parentheses only '()[]{}'`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def is_valid(s):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean isValid(String s) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool isValid(string s) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool isValid(char* s) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"s":"()"}, true),
      tc({"s":"()[]{}"}, true),
      tc({"s":"(]"}, false),
      tc({"s":"([)]"}, false),
      tc({"s":"({[]})"}, true, true),
      tc({"s":"("}, false, true),
    ],
  },
  {
    slug: `implement-queue-using-stacks`,
    title: `Implement Queue using Stacks`,
    difficulty: `Easy`,
    category: `Stack`,
    description: `Implement a FIFO queue using only two stacks. The queue should support \`push\`, \`pop\`, \`peek\`, and \`empty\`.\n\n**Example 1:**\nInput: push(1), push(2), peek(), pop(), empty()\nOutput: 1, 1, false\n\n**Constraints:**\n- 1 ≤ x ≤ 9\n- At most 100 calls will be made.`,
    constraints: `- 1 ≤ x ≤ 9\n- At most 100 calls will be made.`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def MyQueue():\n    # TODO: implement\n    pass`,
      `class Solution {\n  public MyQueue() {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  MyQueue() {\n    // TODO: implement\n    return {};\n  }\n};`,
      `myQueueCreate() {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"ops":["MyQueue","push","push","peek","pop","empty"],"args":[[],[1],[2],[],[],[]]}, [null,null,null,1,1,false]),
      tc({"ops":["MyQueue","push","pop","empty"],"args":[[],[1],[],[]]}, [null,null,1,true], true),
      tc({"ops":["MyQueue","push","push","push","pop","pop","pop","empty"],"args":[[],[1],[2],[3],[],[],[],[]]}, [null,null,null,null,1,2,3,true], true),
    ],
  },
  {
    slug: `longest-substring-without-repeating-characters`,
    title: `Longest Substring Without Repeating Characters`,
    difficulty: `Medium`,
    category: `Sliding Window`,
    description: `Given a string \`s\`, find the length of the longest substring without repeating characters.\n\n**Example 1:**\nInput: s = "abcabcbb"\nOutput: 3\n\n**Example 2:**\nInput: s = "bbbbb"\nOutput: 1\n\n**Constraints:**\n- 0 ≤ s.length ≤ 5·10⁴`,
    constraints: `- 0 ≤ s.length ≤ 5·10⁴`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def length_of_longest_substring(s):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int lengthOfLongestSubstring(String s) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int lengthOfLongestSubstring(string s) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int lengthOfLongestSubstring(char* s) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"s":"abcabcbb"}, 3),
      tc({"s":"bbbbb"}, 1),
      tc({"s":"pwwkew"}, 3),
      tc({"s":""}, 0, true),
      tc({"s":"au"}, 2, true),
      tc({"s":"dvdf"}, 3, true),
    ],
  },
  {
    slug: `3sum`,
    title: `3Sum`,
    difficulty: `Medium`,
    category: `Two Pointers`,
    description: `Given an integer array \`nums\`, return all unique triplets \`[nums[i], nums[j], nums[k]]\` such that i, j, k are distinct and sum to 0.\n\n**Example 1:**\nInput: nums = [-1,0,1,2,-1,-4]\nOutput: [[-1,-1,2],[-1,0,1]]\n\n**Example 2:**\nInput: nums = [0,1,1]\nOutput: []\n\n**Constraints:**\n- 3 ≤ nums.length ≤ 3000\n- -10⁵ ≤ nums[i] ≤ 10⁵`,
    constraints: `- 3 ≤ nums.length ≤ 3000\n- -10⁵ ≤ nums[i] ≤ 10⁵`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def three_sum(nums):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public List<List<Integer>> threeSum(int[] nums) {\n    // TODO: implement\n    return new ArrayList<>();\n  }\n}`,
      `class Solution {\npublic:\n  vector<vector<int>> threeSum(vector<int>& nums) {\n    // TODO: implement\n    return {};\n  }\n};`,
      `int** threeSum(int* nums, int numsSize, int* returnSize, int** returnColumnSizes) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"nums":[-1,0,1,2,-1,-4]}, [[-1,-1,2],[-1,0,1]]),
      tc({"nums":[0,1,1]}, []),
      tc({"nums":[0,0,0]}, [[0,0,0]]),
      tc({"nums":[-2,0,0,2,2]}, [[-2,0,2]], true),
      tc({"nums":[1,2,-2,-1]}, [], true),
    ],
  },
  {
    slug: `add-two-numbers`,
    title: `Add Two Numbers`,
    difficulty: `Medium`,
    category: `Linked List`,
    description: `You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order. Add the two numbers and return the sum as a linked list.\n\n**Example 1:**\nInput: l1 = [2,4,3], l2 = [5,6,4]\nOutput: [7,0,8]\n\n**Constraints:**\n- Number of nodes in each list is in [1, 100]\n- 0 ≤ Node.val ≤ 9`,
    constraints: `- Number of nodes in each list is in [1, 100]\n- 0 ≤ Node.val ≤ 9`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def add_two_numbers(l1, l2):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public ListNode addTwoNumbers(ListNode l1, ListNode l2) {\n    // TODO: implement\n    return new ArrayList<>();\n  }\n}`,
      `class Solution {\npublic:\n  ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {\n    // TODO: implement\n    return nullptr;\n  }\n};`,
      `struct ListNode* addTwoNumbers(struct ListNode* l1, struct ListNode* l2) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"l1":[2,4,3],"l2":[5,6,4]}, [7,0,8]),
      tc({"l1":[0],"l2":[0]}, [0]),
      tc({"l1":[9,9,9,9,9,9,9],"l2":[9,9,9,9]}, [8,9,9,9,0,0,0,1]),
      tc({"l1":[1,8],"l2":[0]}, [1,8], true),
      tc({"l1":[5],"l2":[5]}, [0,1], true),
    ],
  },
  {
    slug: `reverse-linked-list`,
    title: `Reverse Linked List`,
    difficulty: `Medium`,
    category: `Linked List`,
    description: `Given the head of a singly linked list, reverse the list and return the reversed list.\n\n**Example 1:**\nInput: head = [1,2,3,4,5]\nOutput: [5,4,3,2,1]\n\n**Constraints:**\n- Number of nodes in [0, 5000]\n- -5000 ≤ Node.val ≤ 5000`,
    constraints: `- Number of nodes in [0, 5000]\n- -5000 ≤ Node.val ≤ 5000`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def reverse_list(head):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public ListNode reverseList(ListNode head) {\n    // TODO: implement\n    return new ArrayList<>();\n  }\n}`,
      `class Solution {\npublic:\n  ListNode* reverseList(ListNode* head) {\n    // TODO: implement\n    return nullptr;\n  }\n};`,
      `struct ListNode* reverseList(struct ListNode* head) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"head":[1,2,3,4,5]}, [5,4,3,2,1]),
      tc({"head":[1,2]}, [2,1]),
      tc({"head":[]}, []),
      tc({"head":[1]}, [1], true),
      tc({"head":[1,2,3]}, [3,2,1], true),
    ],
  },
  {
    slug: `binary-tree-inorder-traversal`,
    title: `Binary Tree Inorder Traversal`,
    difficulty: `Medium`,
    category: `Trees`,
    description: `Given the root of a binary tree, return the inorder traversal of its nodes' values.\n\n**Example 1:**\nInput: root = [1,null,2,3]\nOutput: [1,3,2]\n\n**Constraints:**\n- Number of nodes in [0, 100]\n- -100 ≤ Node.val ≤ 100`,
    constraints: `- Number of nodes in [0, 100]\n- -100 ≤ Node.val ≤ 100`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def inorder_traversal(root):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public List<Integer> inorderTraversal(TreeNode root) {\n    // TODO: implement\n    return new ArrayList<>();\n  }\n}`,
      `class Solution {\npublic:\n  vector<int> inorderTraversal(TreeNode* root) {\n    // TODO: implement\n    return {};\n  }\n};`,
      `int* inorderTraversal(struct TreeNode* root, int* returnSize) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"root":[1,null,2,3]}, [1,3,2]),
      tc({"root":[]}, []),
      tc({"root":[1]}, [1]),
      tc({"root":[1,2]}, [2,1], true),
      tc({"root":[1,null,3,2]}, [1,2,3], true),
    ],
  },
  {
    slug: `validate-binary-search-tree`,
    title: `Validate Binary Search Tree`,
    difficulty: `Medium`,
    category: `BST`,
    description: `Given the root of a binary tree, determine if it is a valid BST. A BST is valid if the left subtree contains only nodes with values less than the root, and the right subtree contains only values greater than the root.\n\n**Example 1:**\nInput: root = [2,1,3]\nOutput: true\n\n**Example 2:**\nInput: root = [5,1,4,null,null,3,6]\nOutput: false\n\n**Constraints:**\n- Number of nodes in [1, 10⁴]\n- -2³¹ ≤ Node.val ≤ 2³¹-1`,
    constraints: `- Number of nodes in [1, 10⁴]\n- -2³¹ ≤ Node.val ≤ 2³¹-1`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def is_valid_bst(root):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean isValidBST(TreeNode root) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool isValidBST(TreeNode* root) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool isValidBST(struct TreeNode* root) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"root":[2,1,3]}, true),
      tc({"root":[5,1,4,null,null,3,6]}, false),
      tc({"root":[1]}, true),
      tc({"root":[2,2,2]}, false, true),
      tc({"root":[5,4,6,null,null,3,7]}, false, true),
    ],
  },
  {
    slug: `number-of-islands`,
    title: `Number of Islands`,
    difficulty: `Medium`,
    category: `Graphs/DFS-BFS`,
    description: `Given an m x n 2D binary grid \`grid\` containing '1's (land) and '0's (water), count the number of islands. An island is surrounded by water and formed by connecting adjacent lands horizontally or vertically.\n\n**Example 1:**\nInput: grid = [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]\nOutput: 1\n\n**Constraints:**\n- m == grid.length, n == grid[i].length\n- 1 ≤ m, n ≤ 300`,
    constraints: `- m == grid.length, n == grid[i].length\n- 1 ≤ m, n ≤ 300`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def num_islands(grid):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int numIslands(char[][] grid) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int numIslands(vector<vector<char>>& grid) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int numIslands(char** grid, int gridSize, int* gridColSize) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"grid":[["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]}, 1),
      tc({"grid":[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]}, 3),
      tc({"grid":[["1"]]}, 1),
      tc({"grid":[["0"]]}, 0, true),
      tc({"grid":[["1","0","1"],["0","1","0"]]}, 3, true),
    ],
  },
  {
    slug: `clone-graph`,
    title: `Clone Graph`,
    difficulty: `Medium`,
    category: `Graphs/DFS-BFS`,
    description: `Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph. Each node contains a value and a list of neighbors.\n\n**Example 1:**\nInput: adjList = [[2,4],[1,3],[2,4],[1,3]]\nOutput: [[2,4],[1,3],[2,4],[1,3]]\n\n**Constraints:**\n- Number of nodes in [0, 100]\n- 1 ≤ Node.val ≤ 100`,
    constraints: `- Number of nodes in [0, 100]\n- 1 ≤ Node.val ≤ 100`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def clone_graph(node):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public Node cloneGraph(Node node) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  Node* cloneGraph(Node* node) {\n    // TODO: implement\n    return nullptr;\n  }\n};`,
      `struct Node* cloneGraph(struct Node* node) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"adjList":[[2,4],[1,3],[2,4],[1,3]]}, [[2,4],[1,3],[2,4],[1,3]]),
      tc({"adjList":[[]]}, [[]]),
      tc({"adjList":[]}, []),
      tc({"adjList":[[2],[1]]}, [[2],[1]], true),
    ],
  },
  {
    slug: `subsets`,
    title: `Subsets`,
    difficulty: `Medium`,
    category: `Backtracking`,
    description: `Given an integer array \`nums\` of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets.\n\n**Example 1:**\nInput: nums = [1,2,3]\nOutput: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]\n\n**Constraints:**\n- 1 ≤ nums.length ≤ 10\n- -10 ≤ nums[i] ≤ 10`,
    constraints: `- 1 ≤ nums.length ≤ 10\n- -10 ≤ nums[i] ≤ 10`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def subsets(nums):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public List<List<Integer>> subsets(int[] nums) {\n    // TODO: implement\n    return new ArrayList<>();\n  }\n}`,
      `class Solution {\npublic:\n  vector<vector<int>> subsets(vector<int>& nums) {\n    // TODO: implement\n    return {};\n  }\n};`,
      `int** subsets(int* nums, int numsSize, int* returnSize, int** returnColumnSizes) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"nums":[1,2,3]}, [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]),
      tc({"nums":[0]}, [[],[0]]),
      tc({"nums":[1]}, [[],[1]]),
      tc({"nums":[1,2]}, [[],[1],[2],[1,2]], true),
    ],
  },
  {
    slug: `search-in-rotated-sorted-array`,
    title: `Search in Rotated Sorted Array`,
    difficulty: `Medium`,
    category: `Binary Search`,
    description: `There is a sorted array \`nums\` that is rotated at an unknown pivot. Given \`target\`, return its index if found, else -1. Must run in O(log n) time.\n\n**Example 1:**\nInput: nums = [4,5,6,7,0,1,2], target = 0\nOutput: 4\n\n**Constraints:**\n- 1 ≤ nums.length ≤ 5000\n- All values are unique`,
    constraints: `- 1 ≤ nums.length ≤ 5000\n- All values are unique`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def search(nums, target):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int search(int[] nums, int target) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int search(vector<int>& nums, int target) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int search(int* nums, int numsSize, int target) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"nums":[4,5,6,7,0,1,2],"target":0}, 4),
      tc({"nums":[4,5,6,7,0,1,2],"target":3}, -1),
      tc({"nums":[1],"target":0}, -1),
      tc({"nums":[1,3],"target":3}, 1, true),
      tc({"nums":[5,1,3],"target":5}, 0, true),
      tc({"nums":[3,1],"target":1}, 1, true),
    ],
  },
  {
    slug: `jump-game`,
    title: `Jump Game`,
    difficulty: `Medium`,
    category: `Greedy`,
    description: `You are given an array \`nums\` where each element is your maximum jump length at that position. Return \`true\` if you can reach the last index starting from index 0.\n\n**Example 1:**\nInput: nums = [2,3,1,1,4]\nOutput: true\n\n**Example 2:**\nInput: nums = [3,2,1,0,4]\nOutput: false\n\n**Constraints:**\n- 1 ≤ nums.length ≤ 10⁴\n- 0 ≤ nums[i] ≤ 10⁵`,
    constraints: `- 1 ≤ nums.length ≤ 10⁴\n- 0 ≤ nums[i] ≤ 10⁵`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def can_jump(nums):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean canJump(int[] nums) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool canJump(vector<int>& nums) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool canJump(int* nums, int numsSize) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"nums":[2,3,1,1,4]}, true),
      tc({"nums":[3,2,1,0,4]}, false),
      tc({"nums":[0]}, true),
      tc({"nums":[2,0,0]}, true, true),
      tc({"nums":[1,0,1,0]}, false, true),
    ],
  },
  {
    slug: `task-scheduler`,
    title: `Task Scheduler`,
    difficulty: `Medium`,
    category: `Greedy`,
    description: `Given a characters array \`tasks\` (letters A-Z) and an integer \`n\` representing the cooldown period between two same tasks, return the least number of CPU units to finish all tasks.\n\n**Example 1:**\nInput: tasks = ["A","A","A","B","B","B"], n = 2\nOutput: 8\n\n**Constraints:**\n- 1 ≤ tasks.length ≤ 10⁴\n- 0 ≤ n ≤ 100`,
    constraints: `- 1 ≤ tasks.length ≤ 10⁴\n- 0 ≤ n ≤ 100`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def least_interval(tasks, n):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int leastInterval(char[] tasks, int n) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int leastInterval(vector<char>& tasks, int n) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int leastInterval(char* tasks, int tasksSize, int n) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"tasks":["A","A","A","B","B","B"],"n":2}, 8),
      tc({"tasks":["A","C","A","B","D","B"],"n":1}, 6),
      tc({"tasks":["A","A","A","B","B","B"],"n":0}, 6),
      tc({"tasks":["A","A","A","A","A","A"],"n":2}, 16, true),
      tc({"tasks":["A","B","C","D","E","F"],"n":2}, 6, true),
    ],
  },
  {
    slug: `regular-expression-matching`,
    title: `Regular Expression Matching`,
    difficulty: `Hard`,
    category: `DP`,
    description: `Implement regular expression matching with support for '.' (any single character) and '*' (zero or more of the preceding element). The matching must cover the entire input string.\n\n**Example 1:**\nInput: s = "aa", p = "a"\nOutput: false\n\n**Example 2:**\nInput: s = "aa", p = "a*"\nOutput: true\n\n**Constraints:**\n- 1 ≤ s.length, p.length ≤ 20`,
    constraints: `- 1 ≤ s.length, p.length ≤ 20`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def is_match(s, p):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public boolean isMatch(String s, String p) {\n    // TODO: implement\n    return false;\n  }\n}`,
      `class Solution {\npublic:\n  bool isMatch(string s, string p) {\n    // TODO: implement\n    return false;\n  }\n};`,
      `bool isMatch(char* s, char* p) {\n  // TODO: implement\n  return false;\n}`,
    ),
    testCases: [
      tc({"s":"aa","p":"a"}, false),
      tc({"s":"aa","p":"a*"}, true),
      tc({"s":"ab","p":".*"}, true),
      tc({"s":"aab","p":"c*a*b"}, true, true),
      tc({"s":"mississippi","p":"mis*is*p*."}, false, true),
      tc({"s":"ab","p":".*c"}, false, true),
      tc({"s":"aaa","p":"a*a"}, true, true),
      tc({"s":"","p":".*"}, true, true),
    ],
  },
  {
    slug: `edit-distance`,
    title: `Edit Distance`,
    difficulty: `Hard`,
    category: `DP`,
    description: `Given two strings \`word1\` and \`word2\`, return the minimum number of operations (insert, delete, replace) required to convert \`word1\` to \`word2\`.\n\n**Example 1:**\nInput: word1 = "horse", word2 = "ros"\nOutput: 3\n\n**Constraints:**\n- 0 ≤ word1.length, word2.length ≤ 500`,
    constraints: `- 0 ≤ word1.length, word2.length ≤ 500`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def min_distance(word1, word2):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int minDistance(String word1, String word2) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int minDistance(string word1, string word2) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int minDistance(char* word1, char* word2) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"word1":"horse","word2":"ros"}, 3),
      tc({"word1":"intention","word2":"execution"}, 5),
      tc({"word1":"","word2":"a"}, 1),
      tc({"word1":"a","word2":"a"}, 0, true),
      tc({"word1":"abc","word2":"abc"}, 0, true),
      tc({"word1":"ab","word2":"bc"}, 2, true),
    ],
  },
  {
    slug: `alien-dictionary`,
    title: `Alien Dictionary`,
    difficulty: `Hard`,
    category: `Graphs`,
    description: `Given a sorted dictionary of an alien language, find the order of characters. The input is an array of words sorted lexicographically according to the alien alphabet.\n\n**Example 1:**\nInput: words = ["wrt","wrf","er","ett","rftt"]\nOutput: "wertf"\n\n**Constraints:**\n- 1 ≤ words.length ≤ 100\n- 1 ≤ words[i].length ≤ 100`,
    constraints: `- 1 ≤ words.length ≤ 100\n- 1 ≤ words[i].length ≤ 100`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def alien_order(words):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public String alienOrder(String[] words) {\n    // TODO: implement\n    return "";\n  }\n}`,
      `class Solution {\npublic:\n  string alienOrder(vector<string>& words) {\n    // TODO: implement\n    return "";\n  }\n};`,
      `char* alienOrder(char** words, int wordsSize) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"words":["wrt","wrf","er","ett","rftt"]}, "wertf"),
      tc({"words":["z","x"]}, "zx"),
      tc({"words":["z","x","z"]}, ""),
      tc({"words":["a","b","c"]}, "abc", true),
      tc({"words":["ab","adc"]}, "abcd", true),
    ],
  },
  {
    slug: `word-ladder`,
    title: `Word Ladder`,
    difficulty: `Hard`,
    category: `Graphs`,
    description: `Given \`beginWord\`, \`endWord\`, and a dictionary \`wordList\`, return the length of the shortest transformation sequence from beginWord to endWord. Each transformation changes exactly one letter.\n\n**Example 1:**\nInput: beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]\nOutput: 5\n\n**Constraints:**\n- 1 ≤ beginWord.length ≤ 10\n- 1 ≤ wordList.length ≤ 5000`,
    constraints: `- 1 ≤ beginWord.length ≤ 10\n- 1 ≤ wordList.length ≤ 5000`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def ladder_length(begin_word, end_word, word_list):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public int ladderLength(String beginWord, String endWord, List<String> wordList) {\n    // TODO: implement\n    return 0;\n  }\n}`,
      `class Solution {\npublic:\n  int ladderLength(string beginWord, string endWord, vector<string>& wordList) {\n    // TODO: implement\n    return 0;\n  }\n};`,
      `int ladderLength(char* beginWord, char* endWord, char** wordList, int wordListSize) {\n  // TODO: implement\n  return 0;\n}`,
    ),
    testCases: [
      tc({"beginWord":"hit","endWord":"cog","wordList":["hot","dot","dog","lot","log","cog"]}, 5),
      tc({"beginWord":"hit","endWord":"cog","wordList":["hot","dot","dog","lot","log"]}, 0),
      tc({"beginWord":"a","endWord":"c","wordList":["a","b","c"]}, 2),
      tc({"beginWord":"hot","endWord":"dog","wordList":["hot","dog"]}, 0, true),
      tc({"beginWord":"hot","endWord":"hot","wordList":["hot"]}, 1, true),
    ],
  },
  {
    slug: `merge-k-sorted-lists`,
    title: `Merge k Sorted Lists`,
    difficulty: `Hard`,
    category: `Heap/PQ`,
    description: `You are given an array of k linked-lists, each sorted in ascending order. Merge all the linked-lists into one sorted list and return its head.\n\n**Example 1:**\nInput: lists = [[1,4,5],[1,3,4],[2,6]]\nOutput: [1,1,2,3,4,4,5,6]\n\n**Constraints:**\n- k == lists.length\n- 0 ≤ k ≤ 10⁴\n- Each list is sorted in ascending order`,
    constraints: `- k == lists.length\n- 0 ≤ k ≤ 10⁴\n- Each list is sorted in ascending order`,
    examples: [],
    tags: [],
    companies: [],
    hints: [],
    editorial: ``,
    complexity: {"time":"","space":""},
    acceptanceRate: 0,
    submissionCount: 0,
    isPublished: true,
    starterCode: sc(
      `def merge_k_lists(lists):\n    # TODO: implement\n    pass`,
      `class Solution {\n  public ListNode mergeKLists(ListNode[] lists) {\n    // TODO: implement\n    return new ArrayList<>();\n  }\n}`,
      `class Solution {\npublic:\n  ListNode* mergeKLists(vector<ListNode*>& lists) {\n    // TODO: implement\n    return nullptr;\n  }\n};`,
      `struct ListNode* mergeKLists(struct ListNode** lists, int listsSize) {\n  // TODO: implement\n  return NULL;\n}`,
    ),
    testCases: [
      tc({"lists":[[1,4,5],[1,3,4],[2,6]]}, [1,1,2,3,4,4,5,6]),
      tc({"lists":[]}, []),
      tc({"lists":[[]]}, []),
      tc({"lists":[[1]]}, [1], true),
      tc({"lists":[[1,2],[3,4],[5]]}, [1,2,3,4,5], true),
    ],
  },
];

async function main() {
  console.log("Seeding database...");

  // Clear existing problems (cascades to test cases)
  await prisma.testCase.deleteMany();
  await prisma.problem.deleteMany();
  console.log("  Cleared existing problems.\n");

  for (const problem of problems) {
    const { testCases, ...problemData } = problem;
    const created = await prisma.problem.create({
      data: {
        ...problemData,
        testCases: {
          create: testCases.map(tc => ({
            input: tc.input,
            expectedOutput: tc.expectedOutput,
            isHidden: tc.isHidden,
          })),
        },
      },
    });
    console.log("  Created: " + created.title + " (" + created.difficulty + ")");
  }

  console.log("\nSeeded " + problems.length + " problems.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());